# Generated by Django 2.2.12 on 2022-10-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='nam',
            new_name='nama',
        ),
    ]
